DirectoryPath: "tyk-docs/public"
IgnoreAltMissing: true
IgnoreAltEmpty: true
IgnoreDirectoryMissingTrailingSlash: true
CheckInternalHash: true
IgnoreEmptyHref: true
CheckExternal: true
IgnoreURLs:
  - "apps"
  - "^https://github.com/TykTechnologies/tyk-docs"
  - "^https://support.tyk.io"
