DirectoryPath: "tyk-docs/public"
IgnoreAltMissing: true
IgnoreAltEmpty: true
IgnoreDirectoryMissingTrailingSlash: true
CheckInternalHash: false
IgnoreEmptyHref: true
CheckExternal: true
ExternalTimeout: 2
IgnoreURLs:
  - "apps"
