matrix:
  - name: Markdown
    aspell:
      lang: en_US  # Enforces American English
    dictionary:
      wordlists:
        - .wordlist.txt  # Your custom keywords to ignore
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - 'tyk-docs/content/**/*.md'  # Targets all Markdown files in the content directory
    default_encoding: utf-8