matrix:
  - name: Markdown
    aspell:
      aspell:
        lang: en
        d: en_US # American English
    dictionary:
      wordlists:
        - .wordlist.txt  # Custom keywords to ignore
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - tyk-docs/content/tyk-environment-variables.md
      - tyk-docs/content/api-management/client-authentication.md
    default_encoding: utf-8