matrix:
  - name: Markdown
    aspell:
      lang: en_US  # Enforces American English
    dictionary:
      wordlists:
        - .wordlist.txt  # Custom keywords to ignore
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - 'dummy.md'  # Placeholder; will be overridden in the spellcheck Github action
    default_encoding: utf-8