baseurl = "//tyk.io/docs/4.2/"
languageCode = "en-gb"
title = "Tyk Documentation"
theme = "tykio"
MetaDataFormat = "yaml"
enableGitInfo = false
[params]
CanonicalBaseUrl = "https://tyk.io/docs/"
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 2

  [markup.tableOfContents]
    startLevel = 3
    endLevel = 5
    ordered = true
[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]
disableKinds = ["taxonomy", "term"]
[outputFormats.pagesurl]
   mediaType = "application/json"
   baseName = "pagesurl"
   isPlainText = true
   notAlternative = true
[outputs]
  home = ["HTML","pagesurl"]