name: Spellcheck

on:
  pull_request:
    paths:
      - '**/*.md'  # Trigger only if Markdown files change

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get all changed markdown files
        uses: tj-actions/changed-files@v45
        id: changed_files
        with:
          files: |
            **.md
            
      - name: Run Spellcheck
        id: spellcheck
        uses: rojopolis/spellcheck-github-actions@0.47.0
        with:
          task_name: Markdown
          source_files: ${{ steps.changed_files.outputs.all_changed_files }}