name: Spellcheck

on:
  pull_request:
    paths:
      - 'tyk-docs/**/*.md'  # Only run when Markdown files in content/ change

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@0.47.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown