name: Config Generator
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Docs Branch'
        required: true
        default: 'master'
      repoBranch:
        description: 'Project Branch'
        required: true
        default: 'master'
      repo:
        description: 'Project ID. Allowed values: gateway, dashboard, pump'
        required: true
        default: ''

jobs:
  config-gen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: ./tyk-docs
        token: ${{ secrets.ORG_GH_TOKEN }}
        ref: ${{ github.event.inputs.branch }}

    - name: Checkout Config Generator Repo
      uses: actions/checkout@master
      with:
        repository: TykTechnologies/tyk-config-info-generator
        path: ./tyk-config-info-generator
        token: ${{ secrets.ORG_GH_TOKEN }}

    - name: Generate markdown
      run: |
        cd ./tyk-config-info-generator/src
        sudo TOKEN=${{ secrets.ORG_GH_TOKEN }} node app.js ${{ github.event.inputs.repo }}:${{ github.event.inputs.repoBranch }}
        cp /node/home/tyk-config-info-generator/info/${{ github.event.inputs.repoBranch }}/${{ github.event.inputs.repo }}.md ../../tyk-docs/tyk-docs/content/shared/${{ github.event.inputs.repo }}-config.md

    - name: Create configuration changes Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: update config
        title: Updated configuration documentation $REPO:$BRANCH
        body: Updated configuration documentation $REPO:$BRANCH
        branch: update-config-$REPO:$BRANCH
        branch-suffix: random
        delete-branch: true

    - name: Checkout gateway
      if: ${{ github.event.inputs.repo == 'gateway' }}
      uses: actions/checkout@master
      with:
        repository: TykTechnologies/tyk
        path: ./tyk
        token: ${{ secrets.ORG_GH_TOKEN }}
        ref: ${{ github.event.inputs.repoBranch }}

    - name: Copy Swagger
      if: ${{ github.event.inputs.repo == 'gateway' }}
      run: |
        cat ./tyk/swagger.yml > ./tyk-docs/tyk-docs/static/others/gateway-swagger.yml

    - name: Create gateway swagger changes Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: update $REPO:$BRANCH swagger
        title: Updated swagger $REPO:$BRANCH
        body: Updated swagger $REPO:$BRANCH
        branch: update-swagger-$REPO:$BRANCH
        branch-suffix: random
        delete-branch: true

    - name: Checkout dashboard
      if: ${{ github.event.inputs.repo == 'dashboard' }}
      uses: actions/checkout@master
      with:
        repository: TykTechnologies/tyk-analytics
        path: ./tyk-analytics
        token: ${{ secrets.ORG_GH_TOKEN }}
        ref: ${{ github.event.inputs.repoBranch }}

    - name: Copy Swagger
      if: ${{ github.event.inputs.repo == 'dashboard' }}
      run: |
        cat ./tyk-analytics/swagger.yml > ./tyk-docs/tyk-docs/static/others/dashboard-swagger.yml
        cat ./tyk-analytics/swagger-admin.yml > ./tyk-docs/tyk-docs/static/others/dashboard-admin-swagger.yml

    - name: Create dashboard swagger changes Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: update $REPO:$BRANCH swagger
        title: Updated swagger $REPO:$BRANCH
        body: Updated swagger $REPO:$BRANCH
        branch: update-swagger-$REPO:$BRANCH
        branch-suffix: random
        delete-branch: true

