name: Config Generator
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Docs Branch'
        required: true
        default: 'master'
      repoBranch:
        description: 'Project Branch'
        required: true
        default: 'master'
      repo:
        description: 'Project ID. Allowed values: gateway, dashboard'     
        required: true
        default: ''

jobs:
  config-gen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        token: ${{ secrets.REPO_TOKEN }}
        ref: ${{ github.event.inputs.branch }}

    - name: Generate markdown
      run: |
        cd ./scripts/config-generator
        TOKEN=${{ secrets.REPO_TOKEN }} node app.js ${{ github.event.inputs.repo }}:${{ github.event.inputs.repoBranch }}
        cp node/home/tyk-config-info-generator/info/${{ github.event.inputs.repoBranch }}/${{ github.event.inputs.repo }}.md ../../tyk-docs/content/shared/${{ github.event.inputs.repo }}-config.md
        
    - name: Commit change
      env:
        REPO: ${{ github.event.inputs.repo }}
        BRANCH: ${{ github.event.inputs.repoBranch }}
      run: |
          git config --global user.name 'Leonid Bugaev'
          git config --global user.email 'leonsbox@gmail.com'
          git add -A
          git commit -m "Updated configuration documention $REPO:$BRANCH"
          git push
