name: Index update
on: 
  workflow_dispatch:


jobs:
  index:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      API_KEY: ${{ secrets.ALGOLIA_APP_ID }}
      CONFIG: ${{ secrets.ALGOLIA_CONFIG }}
      
    steps:
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v3
      - name: Index
        run: |
          set -e
          docker run -i -e APPLICATION_ID=$APPLICATION_ID -e API_KEY=$API_KEY -e "CONFIG=$CONFIG" algolia/docsearch-scraper

