name: Index update
on: 
  workflow_dispatch:
  # schedule:
  # - cron: "0 * * * *"

jobs:
  index:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      API_KEY: ${{ secrets.ALGOLIA_APP_ID }}
      CONFIG: ${{ secrets.ALGOLIA_CONFIG }}
      
    steps:
      - name: Index
        run: docker run -i -e APPLICATION_ID=$APPLICATION_ID -e API_KEY=$API_KEY -e "CONFIG=$CONFIG" algolia/docsearch-scraper

