name: Test HTML
on:
  pull_request:

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.1'
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0
      - name: Check broken links
        run: |
          cd tyk-docs
          tail -n +2 config.toml > config.toml
          config=$(cat config.toml)
          printf "baseurl = \"/\"\n%b" $config > config.toml
          cat config.toml
          hugo
          cd ..
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
