name: Check maximum nesting level is not exceeded
on: [pull_request]
env:
  MAX_LEVELS: 9

jobs:
  Check-max-levels:
    runs-on: ubuntu-latest
    name: Check-menu-max-levels
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
      - name: "Check navigation level does not exceed the defined maximum"
        run: |
          cd scripts/navigation-levels
          go run main.go --max=$MAX_LEVELS
