name: Import Swagger to Postman using curl

on:
  workflow_dispatch:
    inputs:
      next_latest_branch:
        description: 'The branch to checkout (e.g. release-5.8)'
        required: true

jobs:
  import-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.next_latest_branch }}

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Import Swagger Files to Postman
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_WORKSPACE: ${{ secrets.POSTMAN_WORKSPACE }}
        run: |
          # Define an array of your swagger file names (adjust the path as needed)
          files=(
            "gateway-swagger.yml"
            "dashboard-swagger.yml"
            "mdcb-swagger.yml"
            "enterprise-developer-portal-swagger.yaml"
            "dashboard-admin-swagger.yml"
          )
          
          for file in "${files[@]}"; do
            echo "Processing $file..."
            input=$(cat "tyk-docs/assets/others/$file" | jq -Rs '.')
          
            payload="{\"type\": \"string\", \"input\": $input}"
          
            echo "$payload" > "payload-${file}.json"
            echo "Payload for $file saved to payload-${file}.json"
          
            curl --location --request POST "https://api.getpostman.com/import/openapi?workspace=${POSTMAN_WORKSPACE}" \
              --header "X-Api-Key: ${POSTMAN_API_KEY}" \
              --header "Content-Type: application/json" \
              --data "@payload-${file}.json"
          
            echo "Done processing $file"
          done
