# This GitHub Action is triggered on pull requests to:
# 1. Format changed files using Prettier.
# 2. Automatically install Prettier and its Go template plugin.
# 3. Identify all files changed in the pull request.
# 4. Format the changed files according to Prettier's rules, respecting the .prettierignore file.
# 5. Commit any changes made to the files back to the repository.
# 6. Optionally, check that the files are properly formatted after linting.
#
# This action helps ensure code quality and consistency in documentation and source files.
name: "PR files Formatting"
on:
  workflow_dispatch:
jobs:
  docs_linter:
    runs-on: ubuntu-latest
    name: Format PR files with Prettier
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # Automatically checks out the PR branch
          token: ${{ secrets.ORG_GH_TOKEN }}
      - name: Get Head Commit Message
        id: get_head_commit_message
        run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"

      - name: Check for Skip Linter Marker
        id: check_skip_marker
        run: |
          if [[ "${{ steps.get_head_commit_message.outputs.HEAD_COMMIT_MESSAGE }}" == *"[skip-linter-43n2w]"* ]]; then
            echo "Skipping linter due to marker."
            echo "skip_linter=true" >> "$GITHUB_ENV"  # Set an environment variable
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Install Prettier and dependencies
      - name: Install dependencies
        if: env.skip_linter != 'true'  # Only run if the skip marker is not found
        run: |
          npm install prettier@3.3.3 prettier-plugin-go-template

      # Fetch the base branch and compare changes
      - name: Get changed files
        id: changed-files
        if: env.skip_linter != 'true'  # Only run if the skip marker is not found
        uses: tj-actions/changed-files@v45

      - name: Lint all changed files
        if: env.skip_linter != 'true'  # Only run if the skip marker is not found
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            npx prettier --config .prettierrc --write "$file"
            echo "$file was changed"
          done

      # Auto commit the changes if any
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: env.skip_linter != 'true'  # Only run if the skip marker is not found
        with:
          # skip-linter-43n2w is a Marker to skip rerun of the linter once it makes a commit
          # This prevents cyclic run of the linter
          commit_message: save content formatted by prettier linter [skip-linter-43n2w]

      - name: Check all changed files are linted
        if: env.skip_linter != 'true'  # Only run if the skip marker is not found
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            npx prettier --config .prettierrc --check "$file"
            echo "$file was linted"
          done
