name: Spellcheck Action
on: push

jobs:
  build:
    name: Run rojopolis as a GitHub action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.7.0
      name: Spellcheck
#      with:
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
